# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - newklfnwdkogbewio-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://embeddingcontainerreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4730f011205b42558513e95f77555585 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6669671f878a4847b5a8a7a9ceba25dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: embeddingcontainerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4730f011205b42558513e95f77555585 }}/fruocco/oai-embeddings:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newklfnwdkogbewio-site'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eca98204efd543c6824a1bd5be56cf85 }}
        images: 'embeddingcontainerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4730f011205b42558513e95f77555585 }}/fruocco/oai-embeddings:${{ github.sha }}'