# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kyobogpt-batchfunc

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/sinyunsnag/embeddingsredis/
        username: ${{ secrets.AzureAppService_ContainerUsername_32f00aef46394314a76f43613fd6dae4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1e95b95d28fc40cfbb949d9bf7b34f17 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/sinyunsnag/embeddingsredis/${{ secrets.AzureAppService_ContainerUsername_32f00aef46394314a76f43613fd6dae4 }}/fruocco/oai-batch:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kyobogpt-batchfunc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7f9d57d5b18b4be293d5e39a0a223a4e }}
        images: 'github.com/sinyunsnag/embeddingsredis/${{ secrets.AzureAppService_ContainerUsername_32f00aef46394314a76f43613fd6dae4 }}/fruocco/oai-batch:${{ github.sha }}'